version: "3"

services:
  mongo:
    image: bitnami/mongodb:7.0
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/bitnami/mongodb
    environment:
      - MONGODB_ROOT_USERN=${MONGO_ROOT_USER}
      - MONGODB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGODB_USERNAME=${MONGO_USERNAME}
      - MONGODB_PASSWORD=${MONGO_PASSWORD}
      - MONGODB_DATABASE=${MONGO_DATABASE}

volumes:
  mongodb_data:
    driver: local
