---
openapi: 3.0.3
info:
  title: Communishield
  version: 0.1.0
  description: >
    This application is a security layer for managing user access to files and
    directories based on group memberships and specific permissions. It ensures
    secure authentication and fine-grained authorization for resource access.
  license:
    name: AGPL-3.0
    url: https://www.gnu.org/licenses/agpl-3.0.en.html#license-text
paths:
  /users/login:
    post:
      description: >
        Authenticates users with their login and password. Users must provide a JSON payload containing "login" and "password" fields. Upon successful authentication, it returns a JWT token for accessing protected resources.
      operationId: "login"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Login successful
                  token:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        "401":
          description: Login failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Unauthorized
      tags:
        - Users
  /users/register:
    post:
      description: >
        Registers a new user with their email, login, and password. The request must include a JSON payload with "email", "login", and "password" fields. Upon successful registration, it returns a message indicating that the user was created successfully.
      operationId: "register"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: User registration successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User created successfully
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Invalid request data
      tags:
        - Users
  /groups:
    get:
      description: >
        Returns a list of all groups.
      operationId: "listGroups"
      responses:
        "200":
          description: Groups list
          content:
            application/json:
              schema:
                type: object
                properties:
                  groups:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
      tags:
        - Groups
    post:
      description: >
        Registers a new group with its name. The request must include a JSON payload with "name" field. Upon successful registration, it returns a message indicating that the group was created successfully.
      operationId: "registerGroup"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
      responses:
        "200":
          description: Group created successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Group created
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Invalid request data
      tags:
        - Groups
  /groups/{name}:
    get:
      description: >
        Returns information about a specific group.
      operationId: "getGroup"
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Group details
          content:
            application/json:
              schema:
                type: object
                properties:
                  group:
                    type: object
                    properties:
                      id:
                        type: integer
                      name:
                        type: string
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Invalid request data
      tags:
        - Groups
    delete:
      description: >
        Deletes a specific group.
      operationId: "deleteGroup"
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Group deleted
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Group deleted
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Invalid request data
      tags:
        - Groups
  /groups/{name}/users:
    post:
      description: >
        Adds a user to a specific group.
      operationId: "addUserToGroup"
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
              properties:
                username:
                  type: string
      responses:
        "200":
          description: User added to group
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User added to group
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Invalid request data
      tags:
        - Groups
  /groups/{name}/users/{username}:
    delete:
      description: >
        Removes a user from a specific group.
      operationId: "removeUserFromGroup"
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
        - name: username
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: User removed from group
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User removed from group
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Invalid request data
      tags:
        - Groups
